database:
  user: hanko
  password: hanko
  host: postgres
  port: 5432
  dialect: postgres
passcode:
  email:
    from_address: no-reply@hanko.io
  smtp:
    host: "mailhog"
    port: "2500"
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
server:
  public:
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - 'https://127.0.0.1:5500'
webauthn:
  relying_party:
    origin: "https://127.0.0.1:5500"
